version: 3
profiles: []
hotkeys:
  toggle-window:
    - Ctrl-Space
terminal:
  searchOptions: {}
  customColorSchemes:
    - name: Catppuccin Mocha
      foreground: HSL(226, 64%, 88%)
      background: HSL(240, 21%, 15%)
      selection: null
      cursor: HSL(10, 56%, 91%)
      cursorAccent: null
      colors:
        - HSL(234, 13%, 31%)
        - HSL(343, 81%, 75%)
        - HSL(115, 54%, 76%)
        - HSL(41, 86%, 83%)
        - HSL(217, 92%, 76%)
        - HSL(316, 72%, 86%)
        - HSL(189, 71%, 73%)
        - HSL(226, 64%, 88%)
        - HSL(234, 13%, 36%)
        - HSL(343, 81%, 80%)
        - HSL(115, 54%, 81%)
        - HSL(41, 86%, 88%)
        - HSL(217, 92%, 81%)
        - HSL(316, 72%, 91%)
        - HSL(189, 71%, 78%)
        - HSL(226, 64%, 93%)
  colorScheme:
    # https://github.com/catppuccin/tabby
    name: Catppuccin Mocha
    foreground: HSL(226, 64%, 88%)
    background: HSL(240, 21%, 15%)
    selection: null
    cursor: HSL(10, 56%, 91%)
    cursorAccent: null
    colors:
      - HSL(234, 13%, 31%)
      - HSL(343, 81%, 75%)
      - HSL(115, 54%, 76%)
      - HSL(41, 86%, 83%)
      - HSL(217, 92%, 76%)
      - HSL(316, 72%, 86%)
      - HSL(189, 71%, 73%)
      - HSL(226, 64%, 88%)
      - HSL(234, 13%, 36%)
      - HSL(343, 81%, 80%)
      - HSL(115, 54%, 81%)
      - HSL(41, 86%, 88%)
      - HSL(217, 92%, 81%)
      - HSL(316, 72%, 91%)
      - HSL(189, 71%, 78%)
      - HSL(226, 64%, 93%)
ssh: {}
configSync:
  parts: {}
clickableLinks: {}
accessibility: {}
appearance: {}
hacks: {}
enableWelcomeTab: false
pluginBlacklist: []
