[tools]
# Core languages & runtimes
bun = "latest"
deno = "latest"
elixir = "latest"
erlang = "latest"
ghcup = "latest"
go = "latest"
node = "latest"
rust = "latest"

# Cargo packages
"cargo:fastmod" = "latest"
"cargo:https://github.com/cfbender/venturi" = "latest"
"cargo:https://github.com/nushell/nufmt" = "latest"

# npm packages
"npm:@biomejs/biome" = "latest"
"npm:@getgrit/cli" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@sourcegraph/amp" = "latest"
"npm:@tobilu/qmd" = "latest"
"npm:@withgraphite/graphite-cli" = "latest"

# go packages
"go:github.com/charmbracelet/crush" = "latest"

# Aqua packages
"aqua:pnpm" = "latest"

# CLI tools
ast-grep = "latest"
gum = "latest"
hyperfine = "latest"
opencode = "latest"
rtk = "latest"
task = "latest"
typos = "latest"
yq = "latest"
zellij = "latest"

[settings]
disable_backends = ["asdf"]
experimental = true
idiomatic_version_file_enable_tools = ["rust"]

[settings.npm]
bun = true
