command_timeout = 1000

[cmd_duration]
disabled = true

[memory_usage]
format = '\[$symbol[$ram( | $swap)]($style)\]'

[rust]
format = '\[[$symbol($version)]($style)\]'
symbol = ' '

[elixir]
symbol = " "
