prSections:
  - title: Needs My Review
    filters: is:pr is:open sort:updated-desc draft:false -author:@me -reviewed-by:@me repo:pdq/houston repo:pdq/rover
  - title: My Pull Requests
    filters: is:open author:@me
    layout:
      author:
        hidden: true
repoPaths: # configure where to locate repos when checking out PRs
  pdq/:repo: ~/code/pdq/:repo
theme:
  colors:
    text:
      primary: "#c6d0f5"
      secondary: "#f2d5cf"
      inverted: "#232634"
      faint: "#b5bfe2"
      warning: "#e78284"
      success: "#a6d189"
    background:
      selected: "#414559"
    border:
      primary: "#f2d5cf"
      secondary: "#51576d"
      faint: "#414559"
